dist: bionic

language:
    - c

compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get -y install device-tree-compiler
    - sudo apt-get -y install swig

script:
    - sh build.sh
